export const WOOKIEE_LANGUAGE = {
  birth_year:'rhahrcaoac_roworarc',
  classification: 'oaanraccahwwahoaraaoahoowh',
  cost_in_credits: 'oaoocao_ahwh_oarcwowaahaoc',
  count: 'oaoohuwhao',
  designation: 'wawocahrrwhraaoahoowh',
  director: 'waahrcwooaaooorc',
  films: 'wwahanscc',
  gender: 'rrwowhwaworc',
  manufacturer: 'scrawhhuwwraoaaohurcworc',
  name: 'whrascwo',
  people: 'akwoooakanwo',
  planets: 'akanrawhwoaoc',
  population: 'akooakhuanraaoahoowh',
  producer: 'akrcoowahuoaworc',
  release_date: 'rcwoanworacwo_waraaowo',
  results: 'rcwochuanaoc',
  species: 'cakwooaahwoc',
  starships: 'caorarccacahakc',
  terrain: 'aoworcrcraahwh',
  title: 'aoahaoanwo',
  vehicles: 'howoacahoaanwoc',
}