// export const WOOKIEE_LANGUAGE = {
//   birth_year:'rhahrcaoac_roworarc',
//   characters: 'oaacrarcraoaaoworcc',
//   classification: 'oaanraccahwwahoaraaoahoowh',
//   climate: 'oaanahscraaowo',
//   cost_in_credits: 'oaoocao_ahwh_oarcwowaahaoc',
//   count: 'oaoohuwhao',
//   designation: 'wawocahrrwhraaoahoowh',
//   diameter: 'waahrascwoaoworc',
//   director: 'waahrcwooaaooorc',
//   eye_color: 'worowo_oaooanoorc',
//   films: 'wwahanscc',
//   gender: 'rrwowhwaworc',
//   gravity: 'rrrcrahoahaoro',
//   hair_color: 'acraahrc_oaooanoorc',
//   height: 'acwoahrracao',
//   homeworld: 'acooscwoohoorcanwa',
//   manufacturer: 'scrawhhuwwraoaaohurcworc',
//   mass: 'scracc',
//   max_atmposphering_speed: 'scrak_raaoscoocakacworcahwhrr_cakwowowa',
//   name: 'whrascwo',
//   orbital_period: 'oorcrhahaoraan_akworcahoowa',
//   people: 'akwoooakanwo',
//   pilots: 'akahanooaoc',
//   planets: 'akanrawhwoaoc',
//   population: 'akooakhuanraaoahoowh',
//   producer: 'akrcoowahuoaworc',
//   release_date: 'rcwoanworacwo_waraaowo',
//   residents: 'rcwocahwawowhaoc',
//   results: 'rcwochuanaoc',
//   rotation_period: 'rcooaoraaoahoowh_akworcahoowa',
//   skin_color: 'corahwh_oaooanoorc',
//   species: 'cakwooaahwoc',
//   starships: 'caorarccacahakc',
//   surface_water: 'churcwwraoawo_ohraaoworc',
//   terrain: 'aoworcrcraahwh',
//   title: 'aoahaoanwo',
//   url: 'hurcan',
//   vehicles: 'howoacahoaanwoc',
// }

export const WOOKIEE_ALPHABET = {
  a: 'ra',
  b: 'rh',
  c: 'oa',
  d: 'wa',
  e: 'wo',
  f: 'ww',
  g: 'rr',
  h: 'ac',
  i: 'ah',
  // j
  k: 'or',
  l: 'an',
  m: 'sc',
  n: 'wh',
  o: 'oo',
  p: 'ak',
  // q
  r: 'rc',
  s: 'c',
  t: 'ao',
  u: 'hu',
  v: 'ho',
  w: 'oh',
  x: 'k',
  y: 'ro',
  // z
}